version: 2
jobs:
  build:
    working_directory: ~/clock-in
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run: # run tests
      #     name: test
      #     command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml